### PR TITLE
Fixes `has` false-positive for expired transients

### LINKED ISSUE #4: `has()` wrongly returns true for expired transients
The [`CachePool::has()`][has] method checks if the transient option exists using [`get_option()`][get_option], while [`CachePool::get()`][get] retrieves the value using [`get_transient()`][get_transient].

If a transient has expired but still exists in the options table, calling [`get_transient`][get_transient] will result in the option record being deleted from the database. On the other hand, [`get_option`][get_option] will simple retrieve the value of the expired transient, without deleting it.

Therefore, if a transient has expired, the [`CachePool::has()`][has] method will find the transient and return `true`, while a subsequent [`CachePool::get()`][get] call will delete the transient and return the default value.

[has]: https://github.com/wp-oop/transient-cache/blob/develop/src/CachePool.php#L191
[get]: https://github.com/wp-oop/transient-cache/blob/develop/src/CachePool.php#L63
[get_option]: https://developer.wordpress.org/reference/functions/get_option/
[get_transient]: https://developer.wordpress.org/reference/functions/get_transient/

### PR DESCRIPTION
**Pull request by mecha**
Fixes #4

### CODE REVIEW

File: src/CachePool.php [hunk 1]
```diff
@@ -191,8 +191,7 @@ public function deleteMultiple($keys)
     public function has($key)
     {
         $default = $this->defaultValue;
-        $prefix = $this->getOptionNamePrefix();
-        $value = $this->getOption("{$prefix}{$key}", $default);
+        $value = $this->get($key, $default);
```
Comment (XedinUnknown) [inline src/CachePool.php:194]: As far as I remember, there was some reason why I didn't just do this in the beginning. But I don't remember what it was... Could you kindly consider this again, in case you think of something?

Comment (mecha) [reply src/CachePool.php:194]: I don't know why you wouldn't though. Here are some facts:

1. `get_transient()` **must** be called in order to correctly verify if a transient exists, because its this function that deletes expired transients
2. To check for false negatives, `get_option()` should be used.

The `CachePool::get()` method does both of these, in that order. It's perfect for the job.

Comment (XedinUnknown) [reply src/CachePool.php:194]: Mkay.

**Review by XedinUnknown — APPROVED** [review]
