### PR TITLE
Clear not working

### LINKED ISSUE #11: Wrong Param Type for `get_col()`
in `CachePool::selectColumn()`

```php
$this->wpdb->get_col($query, $columnName);
```

get_col expects an integer, not a string :(
https://developer.wordpress.org/reference/classes/wpdb/get_col/

`phpstan.neon.dist`

```yaml
includes:
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
parameters:
# TODO    level: max
    level: 5
    inferPrivatePropertyTypeFromConstructor: true
    paths:
        - src/
```

### PR DESCRIPTION
**Pull request by XedinUnknown**
## Symptoms
When using `CachePool#clear()`, nothing happens: it silently fails.

## Possible Cause
This is due to 2 things:

1. The [query][1] used in `#getAllKeys()` is incorrect: it puts the variable part of the option name _before_ the prefix. But by definition of the prefix, the variable part has to come after.
2. `#selectColumn()` uses `wpdb#get_col()`, which actually accepts a column _number_ rather than the column _name_. This has been described in #11.

## Suggested Solution
This PR fixes #11 by correcting the query, and adding a userland implementation of column selection.

[1]: https://github.com/wp-oop/transient-cache/blob/develop/src/CachePool.php#L450

### CODE REVIEW

File: src/CachePool.php [hunk 1]
```diff
@@ -466,9 +466,17 @@ protected function getAllKeys(): iterable
...
-        $results = $this->wpdb->get_col($query, $columnName);
+        $results = $this->wpdb->get_results($query, ARRAY_A);
+
+        $column = [];
+        foreach ($results as $row) {
+            $value = array_key_exists($columnName, $row)
+                ? $row[$columnName]
+                : null;
+            $column[] = $value;
+        }
```
Comment (szepeviktor) [inline src/CachePool.php:477]: You've just invented Spanish wax here :)

Comment (XedinUnknown) [reply src/CachePool.php:477]: What's "spanish vax"?

Comment (szepeviktor) [reply src/CachePool.php:477]: ...English says: invented the wheel

Comment (XedinUnknown) [reply src/CachePool.php:477]: Gotcha. Well, I saw your simplifying patch, and LGTM 👍 Gonna go out next release.
